#!/usr/bin/env bash

# Copyright 2020 Tetrate
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "$0" "$@"
echo >&2 docker stderr

# An arg DOCKER_EXIT_CODE=N exits with that code number
while test $# -gt 0; do
	case "$1" in
	DOCKER_EXIT_CODE=*) exit "${1:17}" ;;
	esac
	shift
done
exit 0
