#!/usr/bin/env bash

# Copyright 2020 Tetrate
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "$0" "$@"

printf >&2 '%s\n' "docker stderr"

#
# To simulate exit with an error, pass an argument in the form EXIT_CODE=NN,
# e.g. EXIT_CODE=3
#
exit_code="0"
while test $# -gt 0; do
	case "$1" in
	EXIT_CODE=*)
		exit_code="${1:10}"
		;;
	esac
	shift
done
exit "$exit_code"
