baseurl = "https://func-e.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "func-e"
theme = "hello-friend"

[params]
  defaultTheme = "light"
  showReadingTime = false

[params.logo]
  logoText = "func-e"

[[menu.main]]
  url = "https://github.com/tetratelabs/func-e/blob/master/USAGE.md"
  name = "Usage"
  weight = 20

[[menu.main]]
  url = "https://github.com/tetratelabs/func-e/releases"
  name = "Releases"
  weight = 30

[[menu.main]]
  url = "https://github.com/tetratelabs/func-e"
  name = "GitHub"
  weight = 40
