baseURL = "https://func-e.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "func-e"
theme = "hello-friend"

[params]
  defaultTheme = "light"
  showReadingTime = false

[languages]
  [languages.en]
    [languages.en.params.logo]
      logoText = "func-e"
    [languages.en.menu]
      [[languages.en.menu.main]]
        url = "/learn/"
        identifier = "learn"
        name = "Start Learning"
        weight = 10
      [[languages.en.menu.main]]
        url = "https://github.com/tetratelabs/func-e/blob/master/USAGE.md"
        name = "Usage"
        weight = 20
      [[languages.en.menu.main]]
        url = "https://github.com/tetratelabs/func-e/releases"
        name = "Releases"
        weight = 30
      [[languages.en.menu.main]]
        url = "https://github.com/tetratelabs/func-e"
        name = "GitHub"
        weight = 40
