.nh
.TH func-e 8

.SH NAME
.PP
func-e - Install and run Envoy


.SH SYNOPSIS
.PP
func-e

.PP
.RS

.nf
[--envoy-versions-url]=[value]
[--home-dir]=[value]
[--platform]=[value]

.fi
.RE

.PP
\fBUsage\fP:

.PP
.RS

.nf
To run Envoy, execute `func-e run -c your_envoy_config.yaml`. This
downloads and installs the latest version of Envoy for you.

To list versions of Envoy you can use, execute `func-e versions -a`. To
choose one, invoke `func-e use 1.21.2`. This installs into
`$FUNC_E_HOME/versions/1.21.2`, if not already present. You may also use
minor version, such as `func-e use 1.21`.

You may want to override `$ENVOY_VERSIONS_URL` to supply custom builds or
otherwise control the source of Envoy binaries. When overriding, validate
your JSON first: https://archive.tetratelabs.io/release-versions-schema.json

Advanced:
`FUNC_E_PLATFORM` overrides the host OS and architecture of Envoy binaries.
This value must be constant within a `$FUNC_E_HOME`.

.fi
.RE


.SH GLOBAL OPTIONS
.PP
\fB--envoy-versions-url\fP="": URL of Envoy versions JSON

.PP
\fB--home-dir\fP="": func-e home directory (location of installed versions and run archives)

.PP
\fB--platform\fP="": the host OS and architecture of Envoy binaries. Ex. darwin/arm64


.SH COMMANDS
.SH help
.PP
Shows how to use a [command]

.SH run
.PP
Run Envoy with the given [arguments...] until interrupted

.SH versions
.PP
List Envoy versions

.PP
\fB--all, -a\fP: Show all versions including ones not yet installed

.SH use
.PP
Sets the current [version] used by the "run" command

.SH which
.PP
Prints the path to the Envoy binary used by the "run" command
