#!/bin/bash

set -e

SHFMT_VERSION="3.1.1"
LICENSER_VERSION="0.6.0"
GOLANGCI_LINT_VERSION="1.18.0"

# Install shfmt
wget -c https://github.com/mvdan/sh/releases/download/v${SHFMT_VERSION}/shfmt_v${SHFMT_VERSION}_linux_amd64 -O - | sudo dd of=/usr/bin/shfmt && sudo chmod a+x /usr/bin/shfmt

# Install Licenser
wget -c https://github.com/liamawhite/licenser/releases/download/v${LICENSER_VERSION}/licenser_${LICENSER_VERSION}_Linux_x86_64.tar.gz -O - | sudo tar -xz -C /usr/bin

# Install golangci-lint
curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sudo sh -s -- -b /usr/bin v${GOLANGCI_LINT_VERSION}
