#!/bin/bash

# Install Licenser
wget -c https://github.com/liamawhite/licenser/releases/download/v0.5.1/licenser_0.5.1_Linux_x86_64.tar.gz -O - | sudo tar -xz -C /usr/bin

# Install golangci-lint
go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
