#!/bin/bash

# Install Licenser
wget -c https://github.com/liamawhite/licenser/releases/download/v0.5.1/licenser_0.5.1_Linux_x86_64.tar.gz -O - | sudo tar -xz -C /usr/bin

# Install Proto compiler
wget https://github.com/protocolbuffers/protobuf/releases/download/v3.8.0/protoc-3.8.0-linux-x86_64.zip
unzip protoc-3.8.0-linux-x86_64.zip -d protoc
sudo mv protoc/bin/* /usr/bin/
sudo mv protoc/include/* /usr/include/
rm -rf protoc*

# Install Golang Proto generator
go get -u github.com/golang/protobuf/protoc-gen-go
