#!/bin/bash

SUCCESS=true

# Ensure Licenses are present
if licenser verify -r .; then
    echo "Licenses are present on all recognised files."
else
    echo "Licenses are missing."
    SUCCESS=false
fi

# Ensure Protos are generated and up-to-date
# 
# NOTE: This must be done after license verification as we need to
#       generate licenses as part of proto generation.
find api -type f -name '*.proto' | xargs protoc --go_out=.
licenser apply -r . "Tetrate"
if [ "$(git status --porcelain)" != "" ]; then
    echo "The following Protos need to be regenerated:"
    git status --porcelain -v
    SUCCESS=false
fi


if [ "$SUCCESS" = false ] ; then
    echo "Lint failed."
    exit 1
else
    echo "Lint passed!"
fi
