# `name` value will appear "as is" in the badge.
# See https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository
# yamllint --format github .github/workflows/site.yaml
---
name: "site"

env:
  GO_VERSION: "1.16.4"

on:
  # We run tests on non-tagged pushes to master
  push:
    tags: ''
    branches: master
    paths: 'site/**'
  # We also run tests on pull requests targeted at the master branch.
  pull_request:
    branches: master
    paths: 'site/**'
  # workflow_dispatch will let us manually trigger the workflow from GitHub actions dashboard.
  # For example, you can try to build a branch without raising a pull request.
  # See https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

jobs:
  test:
    name: "Run site tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install Go"
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: "Cache dependencies"
        uses: actions/cache@v2
        with:
          # This combines unrelated caches because actions/cache@v2 doesn't support multiple
          # instances, rather a combined path. https://github.com/actions/cache/issues/16
          path: |
            ~/go/pkg/mod
            ~/go/bin/*-v*
          # '.bingo/*.sum' files generate inconsistently when building `~/go/bin/*-v*`. We key '.bingo/*.mod' instead.
          key: test-${{ runner.os }}-${{ env.GO_VERSION }}-go-${{ hashFiles('go.sum', '.bingo/*.mod') }}
          restore-keys: test-${{ runner.os }}-${{ env.GO_VERSION }}-go-

      - name: "Run site tests"
        run: make test.site
